enum KeyameleonAppMetadata {
    static let bundleIdentifier = "dev.fedemas.keyameleon"
    static let displayName = "Keyameleon"
    static let mainWindowTitle = "Keyameleon"
    static let menuBarAccessibilityLabel = "Keyameleon"
    static let guidedSetupTitle = "Guided setup"
    static let switchingStatusMenuItemPrefix = "Switching Status:"
    static let openMenuItemTitle = "Open Keyameleon…"
    static let continueSetupMenuItemTitle = "Continue Setup…"
    static let openSystemSettingsMenuItemTitle = "Open System Settings"
    static let checkAgainMenuItemTitle = "Check Again"
    static let quitMenuItemTitle = "Quit Keyameleon"
    static let requestPermissionButtonTitle = "Request Permission"
    static let continueWithoutPermissionButtonTitle = "Continue Without Permission"
    static let continueToAssignmentsButtonTitle = "Continue to Assignments"
    static let finishWithoutAssignmentsButtonTitle = "Finish Without Assignments"
    static let assignButtonTitle = "Assign…"
    static let changeAssignmentButtonTitle = "Change Assignment"
    static let removeAssignmentButtonTitle = "Remove Assignment"
    static let replaceSavedPhysicalKeyboardButtonTitle = "Replace Saved Physical Keyboard…"
    static let forgetPhysicalKeyboardButtonTitle = "Forget Physical Keyboard…"
    static let forgetConfirmationTitle = "Forget Physical Keyboard?"
    static let replaceConfirmationTitle = "Replace Saved Physical Keyboard?"
    static let confirmForgetButtonTitle = "Forget"
    static let confirmReplaceButtonTitle = "Replace"
    static let activePhysicalKeyboardLabel = "Active"
    static let physicalKeyboardNameLabel = "Physical Keyboard Name"
    static let keyboardAssignmentLabel = "Keyboard Assignment"
    static let assignmentAppliesAfterActivation = "Applies after next Activation Activity"
    static let assignmentPickerTitle = "Choose Input Source"
    static let assignmentSearchPrompt = "Search Input Sources"
    static let replaceSavedPhysicalKeyboardPickerTitle = "Replace Saved Physical Keyboard"
    static let systemSettingsURL = "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"
    static let uiTestingResetSetupLaunchArgument = "--reset-guided-setup"
    static let settingsMenuItemTitle = "Settings…"
    static let checkForUpdatesMenuItemTitle = "Check for Updates…"
    static let generalSettingsTitle = "General"
    static let launchAtLoginToggleTitle = "Launch at Login"
    static let launchAtLoginFooter =
        "Starts Keyameleon when you log in. Uses Service Management for the main app only."
    static let launchAtLoginErrorMessage =
        "Could not change Launch at Login. Open System Settings → General → Login Items if macOS requires approval."
    static let updatesSettingsSectionTitle = "Updates"
    static let checkForUpdatesButtonTitle = "Check for Updates…"
    static let updateApprovalExplanation =
        "Keyameleon checks for updates at most once every 24 hours on launch. You approve every installation."
    static let criticalUpdateWarningExplanation =
        "A critical update shows a clear warning. Keyameleon still waits for your approval and never forces an update."

    static func switchingStatusMenuItemTitle(_ status: SwitchingStatus) -> String {
        "\(switchingStatusMenuItemPrefix) \(status.displayName)"
    }
}
